import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quizlet Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-950 min-h-screen text-purple-100 overflow-y-hidden`}
      >
        <div className="m-4 flex flex-col h-[calc(100vh-2rem)]">
          <div className="bg-zinc-900/40 w-full p-32 rounded-4xl flex-grow shadow-[0px_0px_30px_6px] shadow-zinc-700/40">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
