import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quizlet Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-950 text-purple-100`}
      >
        
        <div
          className="relative z-10"
          aria-labelledby="modal-title"
          role="dialog"
          aria-modal="true"
        >
          <div className="fixed inset-0 z-10 w-screen overflow-y-auto">
            <div className="flex min-h-full h-screen items-end justify-center p-4 text-center sm:items-center sm:p-0">
              <div className="relative transform overflow-hidden rounded-lg bg-zinc-800 text-left shadow-xl transition-all w-5/6 h-5/6 p-16">
                <div className="flex justify-between">
                  <p className="text-3xl">Create a new set</p>
                  <div>
                    <button className="bg-blue-500 rounded-4xl p-3 pl-8 pr-8 mr-4 cursor-pointer">
                      Save
                    </button>
                    <button className="bg-violet-500 rounded-4xl p-3 pl-8 pr-8 cursor-pointer">
                      Exit
                    </button>
                  </div>
                </div>

                <div className="flex justify-between bg-zinc-700 p-8 rounded-2xl mt-4">
                  <div>
                    <label
                      htmlFor="name"
                      className="block text-sm font-medium text-purple-200"
                    >
                      Set Name:
                    </label>
                    <input
                      name="name"
                      id="name"
                      placeholder="Enter set name"
                      className="mt-1 block w-full rounded-md bg-zinc-700 text-purple-100 border border-zinc-600 p-2"
                    />
                  </div>

                  <div>
                    <label
                      htmlFor="color"
                      className="block text-sm font-medium text-purple-200 mt-4"
                    >
                      Set Color:
                    </label>
                    <input
                      name="color"
                      id="color"
                      type="color"
                      className="mt-1 block w-16 h-10 border-none"
                    />
                  </div>
                </div>

                <div className="flex justify-between bg-zinc-700 p-8 rounded-2xl mt-4">
                  <div>
                    <label
                      htmlFor="front"
                      className="block text-sm font-medium text-purple-200"
                    >
                      Front:
                    </label>
                    <input
                      name="front"
                      id="front"
                      placeholder="Front"
                      className="mt-1 block w-full rounded-md bg-zinc-600 text-purple-100 border border-zinc-500 p-2"
                    />
                  </div>

                  <button className="bg-violet-500 rounded-4xl pl-8 pr-8 cursor-pointer">
                    Add card
                  </button>

                  <div>
                    <label
                      htmlFor="back"
                      className="block text-sm font-medium text-purple-200"
                    >
                      Back:
                    </label>
                    <input
                      name="back"
                      id="back"
                      placeholder="Back:"
                      className="mt-1 block w-full rounded-md bg-zinc-600 text-purple-100 border border-zinc-500 p-2"
                    />
                  </div>
                </div>

                <div className="relative bg-zinc-900/50 mt-6 rounded-xl">
                  <div className="grid grid-cols-1 gap-4 overflow-y-auto p-4 max-h-[60vh]">
                    <div
                      key="sdfdf"
                      className="p-4 rounded-lg bg-zinc-800 items-center flex justify-start"
                    >
                      <span className="text-2xl">1:</span>

                      <div className="flex justify-between flex-grow">
                        <span className="text-2xl ml-12">Hello</span>
                        <span className="text-2xl">I</span>
                        <span className="text-2xl mr-12">Hej</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="min-h-screen overflow-y-hidden">
          <div className="m-4 flex flex-col h-[calc(100vh-2rem)]">
            <div className="bg-zinc-900/40 w-full pt-32 px-32 rounded-4xl flex-grow shadow-[0px_0px_30px_6px] shadow-zinc-700/40">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
